gelsight_mini_node:
  qos:
    reliability: reliable
    history: keep_all
    depth: 10

feats_node:
  qos:
    reliability: reliable
    history: keep_all
    depth: 10

realsense_d405_node:
  qos:
    reliability: reliable
    history: keep_all
    depth: 10

detect_aruco_node:
  qos:
    reliability: reliable
    history: keep_all
    depth: 10


# TODO: add qos settings directly to the packages...