feats_node:
  ros__parameters:
    gs_mini.qos.reliability: reliable
    gs_mini.qos.history: keep_last
    gs_mini.qos.depth: 1

    feats.qos.reliability: reliable
    feats.qos.history: keep_last
    feats.qos.depth: 1